apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: community-plugins
  title: community plugins
  description: backstage community plugins
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: kaulei/community-plugins
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: engineering
